const ActionTypes = {
    USERDATA: 'USERDATA',
    THANKYOUFORORDER: 'THANKYOUFORORDER',
    APPLOADER: 'APPLOADER',
    SERVICEFRMDB: 'SERVICEFRMDB',
    DISCOUNTFRMDB: 'DISCOUNTFRMDB',
    // USER_NUMBER: 'USER_NUMBER'
}

export default ActionTypes;
